name: Docker Image CI

on:
  push:
    branches: [ release ]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: Testbot-wouter

    permissions:
      actions: read
      contents: read
      packages: write
      security-events: read
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      
    - name: login to dockerhub
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: add .env
      shell: bash
      run: |
        touch .env
        echo DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" >> .env
        echo PREFIX="${{ secrets.PREFIX }}" >> .env
        echo CLIENT_ID="${{ secrets.CLIENT_ID }}" >> .env
        echo GUILD_ID="${{ secrets.GUILD_ID }}" >> .env
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/${{ github.repository }}
    
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Pull and run the docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER_IP }}
        username: ${{ secrets.DEPLOYMENT_SERVER_USER }}
        key: ${{ secrets.DEPLOYMENT_SERVER_PK }}
        script: |
          cd /home/github/nerdlandbot_js
          sudo docker-compose pull
          sudo docker-compose up -d
        
