name: standard-js
on:
  push:
    branches: '*'
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  StandardJS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm install
      - run: npm test
